name: AUTO_MATCH
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  flutter_html_iframe: ^3.0.0-beta.2
  carousel_slider: ^4.2.1
  flutter_dotenv: ^5.1.0
  image_cropper: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - lib/.env 
    - assets/page-1/images/logo.png
    - assets/page-1/images/back-arrow.png
    - assets/page-1/images/back-arrow-Qkq.png
    - assets/page-1/images/logo-kmP.png
    - assets/page-1/images/back-arrow-Hoo.png
    - assets/page-1/images/rectangle-1.png
    - assets/page-1/images/back-arrow-oqK.png
    - assets/page-1/images/logo-u53.png
    - assets/page-1/images/icon-message-circle-outline.png
    - assets/page-1/images/logo-Kiy.png
    - assets/page-1/images/back-arrow-CiD.png
    - assets/page-1/images/rectangle-2.png
    - assets/page-1/images/back-arrow-5Wy.png
    - assets/page-1/images/back-arrow-3cD.png
    - assets/page-1/images/back-arrow-ZqT.png
    - assets/page-1/images/icon-message-circle-outline-gpq.png
    - assets/page-1/images/logo-6EV.png
    - assets/page-1/images/logo-Bb7.png
    - assets/page-1/images/logo-n9X.png
    - assets/page-1/images/auto-group-p3yj.png
    - assets/page-1/images/back-arrow-iKs.png
    - assets/page-1/images/back-arrow-jXo.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/icon-bar.png
    - assets/page-1/images/back-arrow-RbP.png
    - assets/page-1/images/icon-heart.png
    - assets/page-1/images/auto-group-lvrb.png
    - assets/page-1/images/icon-bar-4N5.png
    - assets/page-1/images/back-arrow-tth.png
    - assets/page-1/images/group.png
    - assets/page-1/images/group-jGM.png
    - assets/page-1/images/rectangle-2-4ZX.png
    - assets/page-1/images/icon-bar-4vD.png
    - assets/page-1/images/back-arrow-rr5.png
    - assets/page-1/images/icon-eye.png
    - assets/page-1/images/group-HS9.png
    - assets/page-1/images/logo-swP.png
    - assets/page-1/images/logo-CvM.png
    - assets/page-1/images/back-arrow-Zhb.png
    - assets/page-1/images/rectangle-2-89f.png
    - assets/page-1/images/group-54D.png
    - assets/page-1/images/auto-group-gnn3.png
    - assets/page-1/images/icon-bar-6KK.png
    - assets/page-1/images/back-arrow-KPf.png
    - assets/page-1/images/icon-bar-sgV.png
    - assets/page-1/images/back-arrow-d5K.png
    - assets/page-1/images/logo-j2R.png
    - assets/page-1/images/icon-bar-Los.png
    - assets/page-1/images/auto-group-du8o.png
    - assets/page-1/images/logo-2x9.png
    - assets/page-1/images/logo-peu.png
    - assets/page-1/images/rectangle-2-Aw3.png
    - assets/page-1/images/logo-TyK.png
    - assets/page-1/images/icon-eye-off.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
